version: '3.8'

services:
  # Node.js Express server
  node-server:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
    networks:
      - app-network

  # Python FastAPI server
  python-server:
    image: python:3.11-slim
    ports:
      - "8000:8000"
    volumes:
      - ../python-server:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "pip install fastapi uvicorn pydantic &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
